# SPDX-FileCopyrightText: 2022 Johannes Hampp <johannes.hampp@zeu.uni-giessen.de>
#
# SPDX-License-Identifier: MIT

FullDemandList = {
    "DZ": "Algeria",
    "AU": "Australia",
    "CA": "Canada",
    "CN": "China",
    "EG": "Egypt",
    "DE": "Germany",
    "IN": "India",
    "IR": "Iran",
    "JP": "Japan",
    "MY": "Malaysia",
    "MA": "Morocco",
    "SA": "Saudi Arabia",
    "KR": "South Korea",
    "TH": "Thailand",
    "TR": "Turkey",
    "VE": "Venezuela",
    "GB": "United Kingdom",
    "SD": "Sudan",
    "PY": "Paraguay",
    "PL": "Poland",
    "NZ": "New Zealand",
    "AR": "Argentina",
    "PE": "Peru",
    "BR": "Brazil",
    "RU": "Russia",
    "MX": "Mexico",
    "MZ": "Mozambique",
    "NG": "Nigeria",
    "ZA": "South Africa",
    "CO": "Colombia",
    "CL": "Chile",
    "FR": "France",
    "GH": "Ghana",
    "IT": "Italy",
    "ID": "Indonesia",
    "LY": "Libya",
    "ES": "Spain",
    "SE": "Sweden",
    "TN": "Tunisia",
    "UA": "Ukraine",
    "US": "United States",
    "VN": "Vietnam",
}
